// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Project struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	OwnerID     uuid.UUID
	Status      string
	DueDate     sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProjectMember struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      string
	JoinedAt  time.Time
}

type Task struct {
	ID          uuid.UUID
	ProjectID   uuid.UUID
	Title       string
	Description sql.NullString
	Status      string
	Priority    string
	DueDate     sql.NullTime
	CreatedBy   uuid.UUID
	AssignedTo  uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	GoogleID  string
	Email     string
	Name      string
	AvatarUrl sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
