// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, description, owner_id, due_date)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, owner_id, status, due_date, created_at, updated_at
`

type CreateProjectParams struct {
	Name        string
	Description sql.NullString
	OwnerID     uuid.UUID
	DueDate     sql.NullTime
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.DueDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, owner_id, status, due_date, created_at, updated_at FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT project_id, user_id, role, joined_at FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRowContext(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT project_id, user_id, role, joined_at FROM project_members
WHERE project_id = $1
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ProjectMember, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMember
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByMember = `-- name: ListProjectsByMember :many
SELECT p.id, p.name, p.description, p.owner_id, p.status, p.due_date, p.created_at, p.updated_at FROM projects p
INNER JOIN project_members pm ON pm.project_id = p.id
WHERE pm.user_id = $1
`

func (q *Queries) ListProjectsByMember(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, description = $3, status = $4, due_date = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, owner_id, status, due_date, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Status      string
	DueDate     sql.NullTime
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.DueDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
